[linux]
i-06101a19045d951e3 # Linux target (change it before running terraform apply or patching will fail)

[linux:vars]
ansible_connection=community.aws.aws_ssm
ansible_region=us-east-1
ansible_python_interpreter=/usr/bin/python3
ansible_aws_ssm_bucket_name=capstone-vuln-mgmt-ssm-ansible-bucket

[windows]
i-01db4da2c43c5b202

[windows:vars]
ansible_connection=community.aws.aws_ssm
ansible_region=us-east-1
ansible_python_interpreter=/usr/bin/python3
ansible_aws_ssm_bucket_name=capstone-vuln-mgmt-ssm-ansible-bucket
ansible_shell_type=powershell
ansible_aws_ssm_plugin=/usr/local/sessionmanagerplugin/bin/session-manager-plugin